module.exports = {
  Bookmark: require("./Bookmark"),
  ApiUsage: require("./ApiUsage"),
  CachedVideo: require("./CachedVideo"),
  Category: require("./Category"),
  Comment: require("./Comment"),
  Creator: require("./Creator"),
  FeedArticle: require("./FeedArticle"),
  Follow: require("./Follow"),
  Language: require("./Language"),
  Like: require("./Like"),
  Notification: require("./Notification"),
  Recommendation: require("./Recommendation"),
  Reel: require("./Reel"),
  SearchHistory: require("./SearchHistory"),
  SearchUsage: require("./SearchUsage"),
  Share: require("./Share"),
  TrendingKeyword: require("./TrendingKeyword"),
  UserInterest: require("./UserInterest"),
  WatchHistory: require("./WatchHistory"),
};
